// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_Y5UbvgIvJK7dNJv8UnwakwkdDnfKOw',
    appId: '1:79984165965:web:ea3657c70e1054592a8804',
    messagingSenderId: '79984165965',
    projectId: 'angrybirdpro-50d0e',
    authDomain: 'angrybirdpro-50d0e.firebaseapp.com',
    storageBucket: 'angrybirdpro-50d0e.appspot.com',
    measurementId: 'G-R7YPEXLDGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJqNpqr_AyU-0NinN7VLYHtznJXLATXE',
    appId: '1:79984165965:android:a6936d8ef471eb7a2a8804',
    messagingSenderId: '79984165965',
    projectId: 'angrybirdpro-50d0e',
    storageBucket: 'angrybirdpro-50d0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ZeK6iqTYpNWiWksC_LvLeT5XMjsmOFk',
    appId: '1:79984165965:ios:fc4d9c5d764ef4392a8804',
    messagingSenderId: '79984165965',
    projectId: 'angrybirdpro-50d0e',
    storageBucket: 'angrybirdpro-50d0e.appspot.com',
    iosBundleId: 'com.example.drone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ZeK6iqTYpNWiWksC_LvLeT5XMjsmOFk',
    appId: '1:79984165965:ios:ce0d40cd6423648b2a8804',
    messagingSenderId: '79984165965',
    projectId: 'angrybirdpro-50d0e',
    storageBucket: 'angrybirdpro-50d0e.appspot.com',
    iosBundleId: 'com.example.drone.RunnerTests',
  );
}
